/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class RungeKutta */

#ifndef _Included_RungeKutta
#define _Included_RungeKutta
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     RungeKutta
 * Method:    rungekutta
 * Signature: ([Ljava/lang/String;[I[F)[F
 */
JNIEXPORT jfloatArray JNICALL Java_src_seismic_RungeKutta_rungekutta
  (JNIEnv *, jclass, jobjectArray, jintArray, jfloatArray);

#ifdef __cplusplus
}
#endif
#endif
