ALL:
	nvcc -o tti2d_acousticFD Toa_gpu_2dtti_fd_1orderfunction.cu
	nvcc -o tti2d_elasticFD Toa_gpu_2dtti_fd_elastic.cu
	nvcc -o tti2d_acousticRTM Toa_gpu_2dtti_rtm_adcigs_iorderfunciton.cu
clean:
	rm -f *.o *~
